/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controllers.*;
import Model.Member;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;


public class SignupUI extends javax.swing.JFrame {

    
    private SignUpCON cSignup;
    int x;
    
    /**
     * Creates new form SignUp
     */
    public SignupUI() {
        initComponents();
    }
    
    public void close(){
        
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signuppanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        onomavar = new javax.swing.JTextField();
        eponvar = new javax.swing.JTextField();
        phonevar = new javax.swing.JTextField();
        mailvar = new javax.swing.JTextField();
        etosgennisisvar = new javax.swing.JTextField();
        diefthinsivar = new javax.swing.JTextField();
        usernamevar = new javax.swing.JTextField();
        namevar = new javax.swing.JLabel();
        eponimovar = new javax.swing.JLabel();
        kinitovar = new javax.swing.JLabel();
        emailvar = new javax.swing.JLabel();
        etosvar = new javax.swing.JLabel();
        diefthvar = new javax.swing.JLabel();
        uservar2 = new javax.swing.JLabel();
        passwdvar2 = new javax.swing.JLabel();
        passwdvar3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        signupbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        passwd1var = new javax.swing.JPasswordField();
        passwd2var = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        termslabel = new javax.swing.JLabel();
        updatemessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signup = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back2button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signuppanel.setBackground(new java.awt.Color(51, 51, 51));
        signuppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign up");
        signuppanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 50));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        signuppanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 10));

        onomavar.setBackground(new java.awt.Color(51, 51, 51));
        onomavar.setForeground(new java.awt.Color(255, 255, 255));
        onomavar.setBorder(null);
        onomavar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onomavarActionPerformed(evt);
            }
        });
        signuppanel.add(onomavar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 210, 20));

        eponvar.setBackground(new java.awt.Color(51, 51, 51));
        eponvar.setForeground(new java.awt.Color(255, 255, 255));
        eponvar.setBorder(null);
        eponvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eponvarActionPerformed(evt);
            }
        });
        signuppanel.add(eponvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, -1));

        phonevar.setBackground(new java.awt.Color(51, 51, 51));
        phonevar.setForeground(new java.awt.Color(255, 255, 255));
        phonevar.setBorder(null);
        phonevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonevarActionPerformed(evt);
            }
        });
        phonevar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonevarKeyTyped(evt);
            }
        });
        signuppanel.add(phonevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, -1));

        mailvar.setBackground(new java.awt.Color(51, 51, 51));
        mailvar.setForeground(new java.awt.Color(255, 255, 255));
        mailvar.setBorder(null);
        mailvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailvarActionPerformed(evt);
            }
        });
        signuppanel.add(mailvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 220, -1));

        etosgennisisvar.setBackground(new java.awt.Color(51, 51, 51));
        etosgennisisvar.setForeground(new java.awt.Color(255, 255, 255));
        etosgennisisvar.setBorder(null);
        etosgennisisvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etosgennisisvarKeyTyped(evt);
            }
        });
        signuppanel.add(etosgennisisvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 170, 20));

        diefthinsivar.setBackground(new java.awt.Color(51, 51, 51));
        diefthinsivar.setForeground(new java.awt.Color(255, 255, 255));
        diefthinsivar.setBorder(null);
        diefthinsivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diefthinsivarActionPerformed(evt);
            }
        });
        signuppanel.add(diefthinsivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 190, -1));

        usernamevar.setBackground(new java.awt.Color(51, 51, 51));
        usernamevar.setForeground(new java.awt.Color(255, 255, 255));
        usernamevar.setBorder(null);
        usernamevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamevarActionPerformed(evt);
            }
        });
        signuppanel.add(usernamevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, -1));

        namevar.setForeground(new java.awt.Color(255, 255, 255));
        namevar.setText("Όνομα:");
        signuppanel.add(namevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        eponimovar.setForeground(new java.awt.Color(255, 255, 255));
        eponimovar.setText("Επώνυμο:");
        signuppanel.add(eponimovar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        kinitovar.setForeground(new java.awt.Color(255, 255, 255));
        kinitovar.setText("Κινητό:");
        signuppanel.add(kinitovar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        emailvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8_New_Post_32px.png"))); // NOI18N
        signuppanel.add(emailvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        etosvar.setForeground(new java.awt.Color(255, 255, 255));
        etosvar.setText("Έτος γέννησης:");
        signuppanel.add(etosvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        diefthvar.setForeground(new java.awt.Color(255, 255, 255));
        diefthvar.setText("Διεύθυνση:");
        signuppanel.add(diefthvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        uservar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8_User_35px_1.png"))); // NOI18N
        signuppanel.add(uservar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        passwdvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8_Lock_32px.png"))); // NOI18N
        signuppanel.add(passwdvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        passwdvar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8_Lock_32px.png"))); // NOI18N
        signuppanel.add(passwdvar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupbutton.setBackground(new java.awt.Color(0, 0, 0));
        signupbutton.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(255, 255, 255));
        signupbutton.setText("Sign up  ");
        signupbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 2, true));
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        signuppanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 230, 50));
        signuppanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, 20));
        signuppanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, -1));
        signuppanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, -1));
        signuppanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 202, 230, 10));
        signuppanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 10));
        signuppanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, -1));
        signuppanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 230, 10));
        signuppanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, -1));
        signuppanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 230, -1));

        passwd1var.setBackground(new java.awt.Color(51, 51, 51));
        passwd1var.setForeground(new java.awt.Color(255, 255, 255));
        passwd1var.setBorder(null);
        signuppanel.add(passwd1var, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, -1));

        passwd2var.setBackground(new java.awt.Color(51, 51, 51));
        passwd2var.setForeground(new java.awt.Color(255, 255, 255));
        passwd2var.setBorder(null);
        signuppanel.add(passwd2var, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 210, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("By creating an account you aggree to our");
        signuppanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 230, -1));

        termslabel.setForeground(new java.awt.Color(0, 102, 255));
        termslabel.setText("Terms of Service.");
        termslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termslabelMouseClicked(evt);
            }
        });
        signuppanel.add(termslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 190, -1));

        updatemessage.setForeground(new java.awt.Color(255, 51, 51));
        signuppanel.add(updatemessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 230, 20));

        jPanel1.add(signuppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, 550));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        signup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup.setText("     Sign up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        back2button.setBackground(new java.awt.Color(255, 204, 153));
        back2button.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        back2button.setText("Back");
        back2button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 2, true));
        back2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back2button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back2button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/books2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onomavarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onomavarActionPerformed
       
    }//GEN-LAST:event_onomavarActionPerformed

    private void mailvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailvarActionPerformed
        
    }//GEN-LAST:event_mailvarActionPerformed

    private void diefthinsivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diefthinsivarActionPerformed
      
    }//GEN-LAST:event_diefthinsivarActionPerformed

    private void usernamevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamevarActionPerformed
        
    }//GEN-LAST:event_usernamevarActionPerformed

    private void eponvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eponvarActionPerformed
       
    }//GEN-LAST:event_eponvarActionPerformed

    private void phonevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonevarActionPerformed
       
    }//GEN-LAST:event_phonevarActionPerformed

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
         String usersi=usernamevar.getText();
        String passwdsi=passwd1var.getText();
        if((fieldsAreFull()==true) && (passwordsMatch()==true)){
            
            SignUpCON.addnew(usersi, passwdsi);
            close();
            SubmitSuccess subm=new SubmitSuccess();
            subm.setVisible(true);
            
        } else {
            
            boolean pass=passwordsMatch();
            boolean fields=fieldsAreFull();
            if(pass==false){
               updatemessage.setText("Οι κωδικοί δεν ταιριάζουν!");
            }else if(fields==false){
                updatemessage.setText("Πρέπει να συμπληρώσετε όλα τα πεδία");
            }else{
                updatemessage.setText("Δεν μπορεί να πραγματοποιηθεί εγγραφή!");
            }
        } 

    }//GEN-LAST:event_signupbuttonActionPerformed

    private void back2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2buttonActionPerformed
       
        close();
        VivliopwleioMenuUI vil=new VivliopwleioMenuUI();
        vil.setVisible(true);
    }//GEN-LAST:event_back2buttonActionPerformed

    private void termslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termslabelMouseClicked
        
        TermsService terms=new TermsService();
        terms.setVisible(true);
    }//GEN-LAST:event_termslabelMouseClicked

    private void etosgennisisvarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etosgennisisvarKeyTyped
        
        String value = etosgennisisvar.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            etosgennisisvar.setEditable(true);
            updatemessage.setText("");
        } else {
            etosgennisisvar.setEditable(false);
            updatemessage.setText("Συμπληρώστε μόνο αριθμούς!");
        }
    }//GEN-LAST:event_etosgennisisvarKeyTyped

    private void phonevarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonevarKeyTyped
       
        String value2 = phonevar.getText();
        int l2 = value2.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            phonevar.setEditable(true);
            updatemessage.setText("");
        } else {
            phonevar.setEditable(false);
            updatemessage.setText("Συμπληρώστε μόνο αριθμούς!");
        }
        
        if(!(diefthinsivar.getText().equals("") && eponvar.getText().equals("") && etosgennisisvar.getText().equals("") 
            && mailvar.getText().equals("") && onomavar.getText().equals("") && phonevar.getText().equals("") 
            && usernamevar.getText().equals(""))){
                
            
        } else { 
                
                updatemessage.setText("Πρέπει να συμπληρώσετε όλα τα πεδία!");
        }
               
    }//GEN-LAST:event_phonevarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupUI().setVisible(true);
            }
        });
    }
    
    public boolean fieldsAreFull(){
        
        if(!(diefthinsivar.getText().equals("") && eponvar.getText().equals("") && etosgennisisvar.getText().equals("") 
            && mailvar.getText().equals("") && onomavar.getText().equals("") && phonevar.getText().equals("") 
            && usernamevar.getText().equals(""))){
            
            return true;
            
        } else {
            
            updatemessage.setText("Πρέπει να συμπληρώσετε όλα τα πεδία!");
            return false;
        }    
         
    }
    
    public boolean passwordsMatch(){
       if(passwd1var.getText().equals(passwd2var.getText())) {
           
           return true;
           
       } else {
           
           updatemessage.setText("Οι κωδικοί δεν ταιριάζουν!");
            return false;
       }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back2button;
    private javax.swing.JTextField diefthinsivar;
    private javax.swing.JLabel diefthvar;
    private javax.swing.JLabel emailvar;
    private javax.swing.JLabel eponimovar;
    private javax.swing.JTextField eponvar;
    private javax.swing.JTextField etosgennisisvar;
    private javax.swing.JLabel etosvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel kinitovar;
    private javax.swing.JTextField mailvar;
    private javax.swing.JLabel namevar;
    private javax.swing.JTextField onomavar;
    private javax.swing.JPasswordField passwd1var;
    private javax.swing.JPasswordField passwd2var;
    private javax.swing.JLabel passwdvar2;
    private javax.swing.JLabel passwdvar3;
    private javax.swing.JTextField phonevar;
    private javax.swing.JLabel signup;
    private javax.swing.JButton signupbutton;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JLabel termslabel;
    private javax.swing.JLabel updatemessage;
    private javax.swing.JTextField usernamevar;
    private javax.swing.JLabel uservar2;
    // End of variables declaration//GEN-END:variables
}
